export const TICKETS = "GET_TICKETS";
export const TICKET_ACTIVE = "ACTIVE_TICKETS"
export const TICKET_DISABLED = "ACTIVE_DISABLED"
export const TICKET_UPDATE = "ACTIVE_UPDATE"
export const TICKET_DELETE = "ACTIVE_DELETE"